### ISSUE TITLE
rasterio ImportError: DLL load failed while importing _version

### ISSUE THREAD

**Issue by tonyju** [srijithbalakrishnan/dreaminsg-integrated-model#4]
* dreaminsg-integrated-model version:
* Python version:  Python 3.9.12
* Operating System: Win11

### Description

When i install the dependcy python lib rasterio.  ImportError: DLL load failed while importing _version happened.

### What I Did
```
import contextily as ctx
```

**Comment by srijithbalakrishnan** [comment]
Hi,

I think the issue is related to the `rasterio` package which is a dependency of `contextily`. What I would suggest is to remove the `rasterio` and `gdal` packages manually from your environment and try installing from the compatible whl files (for both `gdal` and `rasterio`) from this [UCI respository](https://www.lfd.uci.edu/~gohlke/pythonlibs/ ). Please let me know if it works.
